# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i7PF1a5S2UIJLF1gpQVSf567FEfaQ61f
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, classification_report, mean_absolute_error, r2_score

def run_delivery_full_pipeline(
    file_path,
    target_time_col='Delivery_Time_min',
    distance_col='Distance_km',
    categorical_cols=None,
    numeric_cols=None,
    scaler_type='standard',
    rf_depth=10,
    show_plots=False
):
    if categorical_cols is None:
        categorical_cols = ['Weather', 'Traffic_Level', 'Time_of_Day', 'Vehicle_Type']
    if numeric_cols is None:
        numeric_cols = ['Courier_Experience_yrs']

    # 데이터 로드 (파일은 반드시 필요합니다)
    df = pd.read_csv(file_path)

    if show_plots:
        print("First 5 rows\n", df.head())
        print("\nDataset information\n", df.info())
        print("\nStatistical summary\n", df.describe())

    # 결측치 처리
    for col in categorical_cols:
        if col in df.columns:
            df[col].fillna(df[col].mode()[0], inplace=True)

    for col in numeric_cols:
        if col in df.columns:
            df[col].fillna(df[col].mean(), inplace=True)

    # 인코딩 및 전처리
    if target_time_col in df.columns:
        df['Delivery_Delay'] = (df[target_time_col] > 60).astype(int)

    existing_cat_cols = [col for col in categorical_cols if col in df.columns]
    df_encoded = pd.get_dummies(df, columns=existing_cat_cols, drop_first=True)

    # 스케일러 적용
    scalers = {'standard': StandardScaler(), 'minmax': MinMaxScaler(), 'robust': RobustScaler()}
    selected_scaler = scalers.get(scaler_type.lower(), StandardScaler())

    scaled_array = selected_scaler.fit_transform(df_encoded)
    df_scaled = pd.DataFrame(scaled_array, columns=df_encoded.columns)

    if target_time_col in df.columns:
        df_scaled[target_time_col] = df[target_time_col].values
    if 'Order_ID' in df.columns:
        df_scaled['Order_ID'] = df['Order_ID'].values

    # Classification (동적 3분류)
    if distance_col in df_scaled.columns and target_time_col in df_scaled.columns:
        df_scaled['Distance_Group'] = pd.cut(
            df_scaled[distance_col],
            bins=[0, 5, 10, 15, 20],
            labels=['0-5km', '5-10km', '10-15km', '15-20km']
        )
        df_scaled = df_scaled.dropna(subset=['Distance_Group']).copy()

        df_scaled['Expected_Time'] = df_scaled.groupby('Distance_Group')[target_time_col].transform('median')
        df_scaled['Residual'] = df_scaled[target_time_col] - df_scaled['Expected_Time']

        def label_delay_class(res):
            if res <= 0: return 0
            elif 0 < res <= 20: return 1
            else: return 2

        df_scaled['Delivery_Delay_Class'] = df_scaled['Residual'].apply(label_delay_class)

        drop_cols_clf = ['Order_ID', target_time_col, 'Distance_Group', 'Expected_Time', 'Residual', 'Delivery_Delay_Class', 'Delivery_Delay']
        X_clf = df_scaled.drop(columns=[col for col in drop_cols_clf if col in df_scaled.columns])
        y_clf = df_scaled['Delivery_Delay_Class']

        X_encoded_clf = pd.get_dummies(X_clf, drop_first=False)
        X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(
            X_encoded_clf, y_clf, test_size=0.2, random_state=42, stratify=y_clf
        )

        kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        rf_model = RandomForestClassifier(n_estimators=200, max_depth=rf_depth, random_state=42)

        cv_results_clf = cross_validate(rf_model, X_train_clf, y_train_clf, cv=kfold, scoring=['accuracy'])
        cv_acc = np.mean(cv_results_clf['test_accuracy'])

        rf_model.fit(X_train_clf, y_train_clf)
        y_pred_clf = rf_model.predict(X_test_clf)
        final_acc = accuracy_score(y_test_clf, y_pred_clf)
    else:
        cv_acc, final_acc = 0.0, 0.0

    # Regression (p-value 변수 거름망)
    if target_time_col in df_scaled.columns:
        drop_cols_reg = ['Order_ID', 'Delivery_Delay', 'Distance_Group', 'Expected_Time', 'Residual', 'Delivery_Delay_Class']
        data_reg = df_scaled.drop(columns=[col for col in drop_cols_reg if col in df_scaled.columns])

        X_reg = data_reg.drop(columns=[target_time_col])
        y_reg = data_reg[target_time_col]

        X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
            X_reg, y_reg, test_size=0.2, random_state=42
        )

        X_train_numeric = X_train_reg.astype(float)
        temp_lr = LinearRegression()
        temp_lr.fit(X_train_numeric, y_train_reg)

        predictions = temp_lr.predict(X_train_numeric)
        residuals = y_train_reg - predictions
        X_matrix = np.hstack([np.ones((X_train_numeric.shape[0], 1)), X_train_numeric.values])

        try:
            MSE = np.sum(residuals**2) / (X_matrix.shape[0] - X_matrix.shape[1])
            var_b = MSE * (np.linalg.inv(np.dot(X_matrix.T, X_matrix) + np.eye(X_matrix.shape[1])*1e-5).diagonal())
            sd_b = np.sqrt(var_b)
            coefficients = np.insert(temp_lr.coef_, 0, temp_lr.intercept_)
            ts_b = coefficients / sd_b
            p_values = [2 * (1 - stats.t.cdf(np.abs(i), (X_matrix.shape[0] - X_matrix.shape[1]))) for i in ts_b]
            p_values_dict = dict(zip(X_train_numeric.columns, p_values[1:]))
            dropped_features = [col for col, p_val in p_values_dict.items() if p_val >= 0.05]
        except:
            dropped_features = []

        X_train_selected = X_train_reg.drop(columns=dropped_features)
        X_test_selected = X_test_reg.drop(columns=dropped_features)

        lr_model = LinearRegression()
        lr_model.fit(X_train_selected, y_train_reg)

        y_pred_reg = lr_model.predict(X_test_selected)
        r2 = r2_score(y_test_reg, y_pred_reg)
        mae = mean_absolute_error(y_test_reg, y_pred_reg)
        mape = np.mean(np.abs((y_test_reg - y_pred_reg) / y_test_reg)) * 100
    else:
        r2, mae, mape = 0.0, 0.0, 0.0

    return {
        'scaler': scaler_type.upper(),
        'rf_depth': rf_depth,
        'cv_accuracy': cv_acc,
        'test_accuracy': final_acc,
        'reg_r2': r2,
        'reg_mae': mae,
        'reg_mape': mape
    }

# 자동화 실행 제어 파트
if __name__ == "__main__":
    # 다른 파일로 테스트 시 여기 설정만 변경
    TARGET_FILE = 'Food_Delivery_Times.csv'
    TIME_COL = 'Delivery_Time_min'
    DIST_COL = 'Distance_km'
    CAT_FEATURES = ['Weather', 'Traffic_Level', 'Time_of_Day', 'Vehicle_Type']
    NUM_FEATURES = ['Courier_Experience_yrs']

    scalers_to_try = ['standard', 'minmax', 'robust']
    depth_options = [5, 10, 15]
    all_results = []

    print(f"🔄 데이터셋({TARGET_FILE}) 최적 파이프라인 자동 검색 중...")
    for s_type in scalers_to_try:
        for depth in depth_options:
            res = run_delivery_full_pipeline(
                file_path=TARGET_FILE,
                target_time_col=TIME_COL,
                distance_col=DIST_COL,
                categorical_cols=CAT_FEATURES,
                numeric_cols=NUM_FEATURES,
                scaler_type=s_type,
                rf_depth=depth,
                show_plots=False
            )
            res['combination'] = f"Scaler: {res['scaler']} | RF_Depth: {res['rf_depth']}"
            all_results.append(res)

    summary_df = pd.DataFrame(all_results)
    top_5_combinations = summary_df.sort_values(by='cv_accuracy', ascending=False).head(5)
    best_combination = top_5_combinations.iloc[0]

    print("\n" + "="*75)
    print("🏆 상위 5개 결과 및 가장 좋은 조합 보고서 🏆")
    print("="*75)
    print("\n📊 [TOP 5 조합 성능 비교 성적표]")
    print(top_5_combinations[['combination', 'cv_accuracy', 'test_accuracy', 'reg_r2']].to_string(index=False))

    print("\n" + "-"*75)
    print(f"🥇 [가장 좋은 조합 (Best Combination)]")
    print(f" ➔ 최적의 조합 구성: {best_combination['combination']}")
    print(f" ➔ 분류 교차검증 평균 정확도: {best_combination['cv_accuracy']:.4f} ({best_combination['cv_accuracy']*100:.1f}%)")
    print(f" ➔ 회귀 모델 최종 결정계수(R²): {best_combination['reg_r2']:.4f} ({best_combination['reg_r2']*100:.1f}%)")
    print("="*75)

